---
 - name: ensure docker group
   group: 
     name: '{{ docker_group }}'

 - name: add users to docker group
   user:
     name: "{{ item.key }}"
     append: true
     groups: "{{ docker_group }}"
   with_dict: "{{ docker_users }}"

 - name: ensure docker service running
   service:
     name: '{{ docker_service_name }}'
     enabled: true
     state: started 
